#!/usr/bin/env ruby
# coding: utf-8
#
# chogrep - search cho-directories (obsolete)
#
# Copyright (c) 2014 Kazuto Tominaga
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

$KCODE = 'UTF8' if RUBY_VERSION < '1.9.0'

def main
  system 'chols', '-k', *ARGV if ARGV.size > 0
end

main
