#!/usr/bin/env ruby
# coding: utf-8
$KCODE = 'UTF8' if RUBY_VERSION < '1.9.0'

require 'optparse'

# load my library
Libdir=File.dirname(__FILE__)
require "#{Libdir + '/cholib.rb'}"

def usage
  $stderr.puts "usage: #{File.basename(__FILE__)} [-lksh] <pattern>"
end

def main
  # options
  long = false          # -l
  grep_keywords = false # -k
  case_strict = false   # -s
  help = false          # -h

  opt = OptionParser.new
  opt.on('-l'){|v| long = true}
  opt.on('-k'){|v| grep_keywords = true}
  opt.on('-s'){|v| case_strict = true}
  opt.on('-h'){|v| help = true}
  opt.parse!(ARGV)

  case ARGV.size
  when 0
    pat = //  # matches anything
  when 1
    if case_strict
      pat = Regexp.new(ARGV[0])
    else
      pat = Regexp.new(ARGV[0], Regexp::IGNORECASE)
    end
  else
    usage; exit 1
  end

  open(Cho::CacheFile, "r") do |cf|
    i = 0
    cf.each do |l|
      drpath = l.chomp
      dapath = Cho::ChoHome + '/' + drpath
      if pat =~ File.basename(drpath)
        tfile = dapath + '/' + Cho::TitleFileName
        if File.exist?(tfile)
          title = nil
          open(tfile, "r") do |tf|
            title = tf.gets.chomp
          end
          if long
            ufile = dapath + '/' + Cho::UsedDateFileName
            if File.exist?(ufile)
              utime = nil
              open(ufile, "r") do |uf|
                utime = ' ' + Time.at(uf.gets.to_i).strftime('%Y/%m/%d')
              end
            else
              utime = ' ????/??/??'
            end
          else
            utime = ''
          end
          printf "(%s)%s %s (%s)\n", Cho.numtotag(i) || '  ', utime, title, drpath
          $stdout.flush
        # else: it does not exist (maybe unmounted), but is counted to generate tags
        end
      end
      i += 1
    end
  end
  0
end

main
