#!/usr/bin/env ruby
# coding: utf-8
#
# chotouch - update last-used time of cho-directory
#
# Copyright (c) 2014 Kazuto Tominaga
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

$KCODE = 'UTF8' if RUBY_VERSION < '1.9.0'

# load my library
Libdir=File.dirname(__FILE__)
require "#{Libdir + '/cholib.rb'}"

def usage
  $stderr.puts "usage: #{File.basename(__FILE__)} [<dir>]"
end

def main
  if ARGV.size == 0
    dir = '.'
  elsif ARGV.size == 1
    dir = ARGV[0]
  else
    usage
    exit 1
  end

  if not File.directory?(dir)
    $stderr.puts "#{dir} does not exist"
    exit 1
  end

  Dir.chdir(dir) do
    if not Cho.ischodir?
      $stderr.puts "#{dir} does not seem to be a cho directory"
      exit 1
    end
    Cho.updateusedate
  end

  canondir = Cho.canondir(dir)
  Cho.toplist(canondir)
  0
end

main
